In [ ]:
from torchvision import datasets, transforms
from torch.utils.data import DataLoader

transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5,), (0.5,))  # Normalize to [-1, 1]
])

batch_size = 12

train_dataset = datasets.MNIST(root='./data', train=True, transform=transform, download=True)
test_dataset = datasets.MNIST(root='./data', train=False, transform=transform, download=True)

train_loader = DataLoader(dataset=train_dataset, batch_size=batch_size, shuffle=True)
test_loader = DataLoader(dataset=test_dataset, batch_size=batch_size, shuffle=False)


In [ ]:
len(train_loader) + len(test_loader) * 64

In [ ]:
for each in train_loader:
  print(each)

In [ ]:
import torch

# We first define our model as a Python class and extend it with torch.nn.module


class MNISTModel(torch.nn.Module):
  def __init__(self):
    pass


  def forward(self):
    pass

In [ ]:
class MNISTModel(torch.nn.Module):
  def __init__(self):
    # First layer
    self.first_layer = torch.nn.Linear(28*28, 128)

    # Second layer
    self.second_layer = torch.nn.Linear(128, 64)

    # Third layer
    self.third_layer = torch.nn.Linear(64, 32)

    self.fourth_layer = torch.nn.Linear(32, 10)
    # Activation function
    self.activation_function = torch.nn.ReLU()

In [ ]:
# Then we write the forward

class MNISTModel(torch.nn.Module):
  def __init__(self):
    super(MNISTModel, self).__init__()
    # First layer
    self.first_layer = torch.nn.Linear(28*28, 128)

    # Second layer
    self.second_layer = torch.nn.Linear(128, 64)

    # Third layer
    self.third_layer = torch.nn.Linear(64, 10)

    # Activation function
    self.activation_function = torch.nn.ReLU()


  def forward(self, x):
    x = x.view(-1, 28*28)
    x = self.activation_function(self.first_layer(x))
    x = self.activation_function(self.second_layer(x))
    x = self.activation_function(self.third_layer(x))
    x = self.fourth_layer(x)
    return x

In [ ]:
model = MNISTModel()
loss_fn = torch.nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=0.001)
num_epochs = 5

# Training loop
for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0
    for batch_idx, (data, targets) in enumerate(train_loader):

        # Forward pass
        outputs = model(data)
        loss = loss_fn(outputs, targets)

        # Backward pass and optimization
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

        if batch_idx % 100 == 0:
            print(f'Epoch [{epoch+1}/{num_epochs}], Step [{batch_idx}/{len(train_loader)}], Loss: {loss.item():.4f}')

    print(f'Epoch [{epoch+1}/{num_epochs}], Average Loss: {running_loss / len(train_loader):.4f}')


Epoch [1/5], Step [0/938], Loss: 2.3036
Epoch [1/5], Step [100/938], Loss: 0.6224
Epoch [1/5], Step [200/938], Loss: 0.5134
Epoch [1/5], Step [300/938], Loss: 0.3314
Epoch [1/5], Step [400/938], Loss: 0.2024
Epoch [1/5], Step [500/938], Loss: 0.2174
Epoch [1/5], Step [600/938], Loss: 0.5180
Epoch [1/5], Step [700/938], Loss: 0.2825
Epoch [1/5], Step [800/938], Loss: 0.1569
Epoch [1/5], Step [900/938], Loss: 0.1930
Epoch [1/5], Average Loss: 0.4019
Epoch [2/5], Step [0/938], Loss: 0.2790
Epoch [2/5], Step [100/938], Loss: 0.2154
Epoch [2/5], Step [200/938], Loss: 0.0595
Epoch [2/5], Step [300/938], Loss: 0.1370
Epoch [2/5], Step [400/938], Loss: 0.1311
Epoch [2/5], Step [500/938], Loss: 0.0744
Epoch [2/5], Step [600/938], Loss: 0.1975
Epoch [2/5], Step [700/938], Loss: 0.2803
Epoch [2/5], Step [800/938], Loss: 0.2113
Epoch [2/5], Step [900/938], Loss: 0.0753
Epoch [2/5], Average Loss: 0.1908
Epoch [3/5], Step [0/938], Loss: 0.0861
Epoch [3/5], Step [100/938], Loss: 0.1279
Epoch [3/5], S

In [ ]:
model.eval()
correct = 0
total = 0
with torch.no_grad():
    for data, targets in test_loader:
        outputs = model(data)
        _, predicted = torch.max(outputs.data, 1)
        total += targets.size(0)
        correct += (predicted == targets).sum().item()

print(f'Accuracy of the model on the 10,000 test images: {100 * correct / total:.2f}%')

Accuracy of the model on the 10,000 test images: 96.78%


In [ ]:
a = torch.rand(10, 5)
print(a)

a = a.view(-1, 10 * 5)
a

tensor([[0.4064, 0.3312, 0.8419, 0.7802, 0.9119],
        [0.3690, 0.2914, 0.3996, 0.5768, 0.7479],
        [0.0143, 0.8874, 0.9925, 0.6210, 0.4405],
        [0.5767, 0.5619, 0.8360, 0.9591, 0.2719],
        [0.4766, 0.5071, 0.5838, 0.0367, 0.3478],
        [0.4404, 0.2684, 0.3274, 0.5014, 0.5796],
        [0.0068, 0.0408, 0.3626, 0.4348, 0.1615],
        [0.7236, 0.6786, 0.3476, 0.2048, 0.0282],
        [0.3578, 0.7517, 0.1073, 0.8107, 0.8765],
        [0.7310, 0.7558, 0.5232, 0.5516, 0.1495]])


tensor([[0.4064, 0.3312, 0.8419, 0.7802, 0.9119, 0.3690, 0.2914, 0.3996, 0.5768,
         0.7479, 0.0143, 0.8874, 0.9925, 0.6210, 0.4405, 0.5767, 0.5619, 0.8360,
         0.9591, 0.2719, 0.4766, 0.5071, 0.5838, 0.0367, 0.3478, 0.4404, 0.2684,
         0.3274, 0.5014, 0.5796, 0.0068, 0.0408, 0.3626, 0.4348, 0.1615, 0.7236,
         0.6786, 0.3476, 0.2048, 0.0282, 0.3578, 0.7517, 0.1073, 0.8107, 0.8765,
         0.7310, 0.7558, 0.5232, 0.5516, 0.1495]])

In [ ]:
first_data = test_loader.dataset[0]
data, target = first_data

output = model(data)
print(output, target)

tensor([[ -2.2572,  -5.8984,   0.5959,   1.1435,  -5.3354,  -8.3261, -18.1191,
          11.2509,  -5.3829,   1.9465]], grad_fn=<AddmmBackward0>) 7
